
let types = {
    DISABLEAOS : "DISABLE_AOS",
    ENABLEAOS : "ENABLE_AOS",
    ADMINLOGIN : "ADMIN_LOGIN",
    ADMINLOGOUT : "ADMIN_LOGOUT",
    OPENSEARCH : "OPEN_SEARCH",
    CLOSESEARCH : "CLOSE_SEARCH",
    CHANGEFONT : "CHANGE_FONT",
    USERLOGIN : "USER_LOGIN",
    USERLOGOUT : "USER_LOGOUT",
    ADDTOLIKELIST : "ADD_TO_LIKE_LIST",
    REMOVELIKELIST : "REMOVE_LIKE_LIST",
    VIETNAMESE : "VIETNAMESE",
    ENGLISH : "ENGLISH"
}

export default types